export const CONTEXT_UPDATE_STATE = 'CONTEXT_UPDATE_STATE';
export const CONTEXT_TOGGLE_STATE = 'CONTEXT_TOGGLE_STATE';
export const CONTEXT_APPEND_ARRAY = 'CONTEXT_APPEND_ARRAY';
export const CONTEXT_UPDATE_ARRAY = 'CONTEXT_UPDATE_ARRAY';
export const CONTEXT_DELETE_ARRAY = 'CONTEXT_DELETE_ARRAY';